User's Guide
------------

.. toctree::
   :maxdepth: 2

   installation
   quickstart

API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 3

   api

Additional Notes
----------------

Design notes, legal information and changelog are here for the interested.

.. toctree::
   :maxdepth: 2

   license

.. bibliography:: refs.bib
   :style: unsrt
   :all: